# Generated by Django 3.0 on 2019-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemEval2010Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.CharField(max_length=500)),
                ('entity1_idx', models.IntegerField()),
                ('entity2_idx', models.IntegerField()),
                ('entity1', models.CharField(max_length=200)),
                ('entity2', models.CharField(max_length=200)),
                ('relation', models.IntegerField()),
                ('trigger_center', models.IntegerField(null=True)),
                ('is_train', models.BooleanField(default=True)),
                ('trigger_words', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SemEval2010Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
